repos:
  - repo: local
    hooks:
      - id: cargo-nightly-fmt
        name: cargo +nightly fmt
        entry: cargo +nightly fmt --all -- --check
        language: system
        types: [rust]
        pass_filenames: false # 이거도 붙여두면 안전

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false # 핵심!
